Repository Manta-Network/sdk, pull requests merged in 2023-04, with the labels that each got.

#115 Upgrade to v0.5.14
  CHANGELOG.md
  manta-js/docs/how-to-use-manta-js-sdk.md
  manta-js/examples/extension-example/src/App.tsx
  manta-js/examples/sdk-example/index.ts
  manta-js/package/package.json
  manta-js/package/src/BaseWallet.ts
  manta-js/package/src/PrivateWallet.ts
  manta-js/package/src/interfaces.ts
  manta-js/package/src/pallets/MantaPayWallet.ts
  manta-js/package/src/pallets/MantaSbtWallet.ts
  manta-js/package/src/wallet/crate/Cargo.toml
  manta-js/package/src/wallet/crate/src/lib.rs
Labels: L-added

#119 Fix/download file bug
  CHANGELOG.md
  manta-js/examples/extension-example/src/App.tsx
  manta-js/examples/sdk-example/index.ts
  manta-js/examples/sdk-example/package.json
  manta-js/package/package.json
  manta-js/package/src/BaseWallet.ts
  manta-js/package/src/PrivateWallet.ts
  manta-js/package/src/interfaces.ts
  manta-js/package/src/ledger-api/index.ts
  manta-js/package/src/pallets/MantaPayWallet.ts
  manta-js/package/src/utils.ts
  manta-js/package/src/wallet/crate/src/lib.rs
Labels: L-fixed, L-added

#118 Pruning
  CHANGELOG.md
  manta-js/examples/extension-example/src/App.tsx
  manta-js/examples/extension-example/src/interfaces.ts
  manta-js/examples/sdk-example/index.ts
  manta-js/package/package.json
  manta-js/package/src/BaseWallet.ts
  manta-js/package/src/PrivateWallet.ts
  manta-js/package/src/interfaces.ts
  manta-js/package/src/ledger-api/index.ts
  manta-js/package/src/pallets/MantaPayWallet.ts
  manta-js/package/src/pallets/MantaSbtWallet.ts
  manta-js/package/src/utils/TaskSchedule.ts
  manta-js/package/src/utils/index.ts
  manta-js/package/src/wallet/crate/Cargo.toml
  manta-js/package/src/wallet/crate/src/lib.rs
  manta-js/package/src/wallet/crate/src/types.rs
Labels: L-added

#124 Upgrade to 0.5.15
  CHANGELOG.md
  manta-js/examples/sdk-example/index.ts
  manta-js/package/package.json
  manta-js/package/src/wallet/crate/Cargo.toml
Labels: L-changed
