Repository Manta-Network/sdk, pull requests merged in 2023-02, with the labels that each got.

#65 Support Node.js
  manta-js/README.md
  manta-js/examples/asset-webpack-ts/yarn.lock
  manta-js/package/package.json
  manta-js/package/tsconfig.json
  manta-js/tsconfig.json
Labels: C-enhancement, A-compatibility

#84 feat: add changelog and release system
  .github/PULL_REQUEST_TEMPLATE.md
  .github/RELEASE_TEMPLATE.md
  .github/release.yml
  .github/workflows/release.yml
  CHANGELOG.md
Labels: L-skip

#85 Key Dependent Signer Function APIs
  manta-js/CHANGELOG.md
  manta-js/examples/asset-webpack-ts/index.ts
  manta-js/examples/asset-webpack-ts/package.json
  manta-js/examples/asset-webpack-ts/yarn.lock
  manta-js/package/src/api/index.js
  manta-js/package/src/privateWallet.ts
  manta-js/package/src/sdk.interfaces.ts
  manta-js/package/src/wallet/crate/Cargo.toml
  manta-js/package/src/wallet/crate/src/lib.rs
  manta-js/package/src/wallet/yarn.lock
  manta-js/package/yarn.lock
Labels: L-added

#86 init private wallet without connected api
  manta-js/CHANGELOG.md
  manta-js/README.md
  manta-js/examples/asset-webpack-ts/index.ts
  manta-js/package/package.json
  manta-js/package/src/privateWallet.ts
Labels: L-changed
