Repository Manta-Network/sdk, pull requests merged in 2023-03, with the labels that each got.

#102 Include Sinks in ToPublic Transaction
  manta-js/CHANGELOG.md
  manta-js/examples/asset-webpack-ts/index.ts
  manta-js/examples/asset-webpack-ts/yarn.lock
  manta-js/package/package.json
  manta-js/package/src/api/index.js
  manta-js/package/src/manta-config.json
  manta-js/package/src/privateWallet.ts
  manta-js/package/src/utils.ts
  manta-js/package/src/wallet/crate/Cargo.toml
  manta-js/package/src/wallet/crate/src/lib.rs
Labels: C-enhancement, L-changed, A-serialization, A-compatibility

#105 Save while syncing
  manta-js/CHANGELOG.md
  manta-js/examples/asset-webpack-ts/index.ts
  manta-js/examples/asset-webpack-ts/package.json
  manta-js/examples/asset-webpack-ts/webpack.config.js
  manta-js/examples/asset-webpack-ts/yarn.lock
  manta-js/package/package.json
  manta-js/package/src/api/index.js
  manta-js/package/src/manta-config.json
  manta-js/package/src/privateWallet.ts
  manta-js/package/src/sdk.interfaces.ts
  manta-js/package/src/utils.ts
  manta-js/package/src/wallet/crate/Cargo.toml
  manta-js/package/src/wallet/crate/src/lib.rs
  manta-js/package/yarn.lock
Labels: L-added

#72 Helper for xcm remote transact payload
  manta-js/examples/asset-webpack-ts/index.ts
  manta-js/package/src/privateWallet.ts
  manta-js/package/src/utils.ts
  manta-js/package/yarn.lock
Labels: C-enhancement

#108 Initial signer sync
  manta-js/CHANGELOG.md
  manta-js/examples/asset-webpack-ts/index.ts
  manta-js/examples/asset-webpack-ts/package.json
  manta-js/examples/asset-webpack-ts/yarn.lock
  manta-js/package/package.json
  manta-js/package/src/api/index.js
  manta-js/package/src/manta-config.json
  manta-js/package/src/privateWallet.ts
  manta-js/package/src/sdk.interfaces.ts
  manta-js/package/src/utils.ts
  manta-js/package/src/wallet/crate/Cargo.toml
  manta-js/package/src/wallet/crate/src/lib.rs
  manta-js/package/src/wallet/crate/src/types.rs
  manta-js/package/yarn.lock
Labels: L-added
